# Generated by Django 2.0.5 on 2018-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone_num',
            field=models.IntegerField(default=1, max_length=30, null=0),
        ),
    ]
