# Generated by Django 2.0.5 on 2018-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0002_auto_20180603_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.FileField(upload_to='images/%y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_num',
            field=models.IntegerField(default=1, null=0),
        ),
    ]
