# Generated by Django 2.0.5 on 2018-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0003_auto_20180604_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='pic_encode',
            field=models.TextField(null='0'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(upload_to='data_analysis/uploadfile'),
        ),
    ]
