# Generated by Django 2.0.5 on 2018-06-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0005_members_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='members',
            name='attend',
            field=models.IntegerField(default=0, null=0),
        ),
        migrations.AddField(
            model_name='members',
            name='imagefile',
            field=models.FileField(default='NO_PIC', null='1', upload_to='data_analysis/uploadfile'),
        ),
        migrations.AlterField(
            model_name='members',
            name='job',
            field=models.CharField(default='학생', max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(default='pjh', max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='passwd',
            field=models.CharField(default='0000', max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='members',
            name='pic_encode',
            field=models.TextField(default='0', null='0'),
        ),
    ]
