# Generated by Django 2.0.5 on 2018-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0006_auto_20180607_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='attend',
            field=models.CharField(default='0', max_length=30, null='0'),
        ),
    ]
