# Generated by Django 2.0.5 on 2018-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isa', '0007_auto_20180607_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.TextField(default='none', null='none')),
                ('sub_name', models.CharField(default='none', max_length=50, null='none')),
                ('pro_name', models.CharField(default='none', max_length=50, null='none')),
            ],
        ),
    ]
